---
title: Kid's Cup of Rochester
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: kidscuprochester@gmail.com
description: Kid's Cup Rochester Golf Tournament
baseurl: "/"
url: https://kidscuprochester.github.io
markdown: kramdown
plugins:
- jekyll-feed
intro:
  image: "/uploads/golf_course.jpg"
next_event:
  date: 2018-05-21 00:00:00.000000000 Z
  time: 9:30 - 6:00 PM
  location: Somerby Golf Club
  directions_url: https://www.google.com/maps/dir//''/@44.0477542,-92.6697751,13z/data=!4m8!4m7!1m0!1m5!1m1!1s0x87f742b8acef5c79:0xe0c57d3c2c3b35dd!2m2!1d-92.6347557!2d44.0476979
who_we_are:
  text: |
    Thanks to the vision of Mark and Sheryl Tasler, what began in 1997 as the Miracle Marathon evolved into the Kid’s Cup Golf Tournament.

    In its 22nd year, the tournament has raised over $1.5 million benefitting children for more than two decades.  Mayo Clinic Children’s Center and Gillette Children’s Hospital were the original recipients.

    Beginning in 2012 all Kid’s Cup donations remain local benefitting Mayo Clinic Children’s Center and Prenatal and Infant Care at Olmsted Medical Center.  100% of the money raised goes directly to these two organizations.
  image: "/uploads/players_1.jpg"
what_makes_us_unique:
  top_text: |
    For 22 years our golfers have been raising money for the kids.  Golfers raise a minimum of $500. Many go above and beyond the required $500 and raise up to $6,000 a year.

    When you are asked to donate to a Kid’s Cup golfer, you are donating to fund a project or product that may not otherwise happen.   The mission of our tournament is to make an impact on children’s stay at the hospital, not only for the patients but for their parents and siblings. They are generally lengthy stays, and the money raised goes to make these stays more tolerable and comfortable.
  top_image: "/uploads/golf_cart_1.jpg"
  middle_text: |
    Over the years, the projects at Mayo Clinic have included:

    * Cast room pictures printer
    * Marking milestones in the Neonatal NICU
    * iPads
    * Sibling support bags
    * Shaken baby syndrome prevention program
    * Equipment for PMR Med Peds
    * Wild Encounters ZooMobile
    * NICU stay-cations
    * Fingerprint charms
    * Sensory Music and Push Button Toys
    * Simulation dolls
    * Devices to ease blood draws
  middle_image: "/uploads/mayo_check.jpg"
  bottom_text: |
    In 2011, a project called “Beads of Courage” was funded at Mayo Clinic.  Beads of Courage are handed to each child who has any type of procedure whether it is a needle stick all the way to a successful day of chemotherapy.

    Just imagine how many beads these kids collect over their time or trips to the hospital.  With each visit, the strings of courage beads get longer, and each bead garners a smile on a hurting or ill child.
  bottom_image: 
whats_new:
  text: |
    The Kid's Cup has followed the same format for 21 years, but this year we've decided to switch things up. Instead of 36 holes played at two different golf courses, the tournament will be held at [Somerby Golf Club](http://www.somerby.com), South East Minnesota's premiere championship golf club, on May 21, 2018

    The tournament will be 18 holes, leaving more time for our golfers to enjoy dinner, along with our silent auction.

    ##### Schedule of Events:

    * 9:30 AM - Registration and hot breakfast buffet
    * 11:00 AM - Shotgun start
    * 3:30 PM - Social hour and silent auction
    * 4:30 PM - Dinner (chef-carved prime rib) and awards
  image: "/uploads/somerbys_course.jpg"
sign_up:
  for_golfers:
    text: 'Registration is easy. Simply create your fund easy page [here](https://secure.ministrysync.com/ministrysync/event/website/home/?e=10087).
      Once registered, you can direct potential donors to your site and share the
      link on Facebook and Twitter.  If you receive donations as cash or check, simply
      record the donations on your Fund Easy page, and bring the cash and checks to
      Somerby the day of the event.

'
    button_link: https://secure.ministrysync.com/ministrysync/event/website/home/?e=10088
    button_text: I want to golf!
  for_sponsors:
    text: 'We understand that not everyone is a golfer. However, there are sponsorship
      opportunities available, along with volunteer opportunities. For more information
      contact Jeff Jensen ([jeff.jensen@expresspros.com](mailto:jeff.jensen@expresspros.com?subject=Kid''s
      Cup Rochester Sponsorship)) or Marge Kelley ([marge.kelley@expresspros.com](mailto:marge.kelley@expresspros.com?subject=Kid''s
      Cup Rochester Sponsorship)).

'
    button_link: mailto:marge.kelley@expresspros.com?subject=Kid's Cup Rochester Sponsorship
    button_text: I want to sponsor!
presenting_sponsors:
- image: "/uploads/express_logo.png"
  name: Express Employment Professionals
  link: https://www.expresspros.com/
corporate_sponsors:
- image: "/uploads/somerby_logo.jpg"
  name: Somerby Golf Club
  link: http://www.somerby.com/
- image: "/uploads/edina_logo.jpg"
  name: Edina Realty Rochester
  link: https://www.edinarealty.com
other_sponsors:
- image: "/uploads/sams_club_logo.png"
  name: Sam's Club
  link: https://samsclub.com
- image: "/uploads/iheart_media_logo.png"
  name: iHeart Media
  link: https://www.iheartmedia.com/iheartmedia/stations?city=Rochester
- image: "/uploads/pro_image_logo.png"
  name: Pro Image
  link: http://www.proimageroch.com
