---
title: Kid's Cup of Rochester
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: kidscuprochester@gmail.com
description: Kid's Cup Rochester Golf Tournament
baseurl: "/"
url: https://kidscuprochester.github.io
markdown: kramdown
plugins:
- jekyll-feed
intro:
  image: "/uploads/golf_course.jpg"
next_event:
  date: 2019-05-20 00:00:00.000000000 Z
  time: 9:30 - 6:00 PM
  location: Somerby Golf Club
  directions_url: https://www.google.com/maps/dir//''/@44.0477542,-92.6697751,13z/data=!4m8!4m7!1m0!1m5!1m1!1s0x87f742b8acef5c79:0xe0c57d3c2c3b35dd!2m2!1d-92.6347557!2d44.0476979
who_we_are:
  text: |-
    Now in its 23rd year, the Kid’s Cup Golf Tournament
    has raised over $1.5 million benefitting children at
    Mayo Clinic Children’s Center and Prenatal and Infant Care at Olmsted Medical Center.

    Golfers are asked to raise a minimum of $500 in pledges. Several golfers raised more than $2,000! In 2018, with 100 golfers, Kid’s Cup Golf Tournament raised more than $77,000. 100% of the pledges collected goes directly to fund programs at Mayo Clinic Children’s Center and Olmsted Medical Center.
  image: "/uploads/players_1.jpg"
whats_new:
  text: |
    The tournament will be held at [Somerby Golf Club](http://www.somerby.com), South East Minnesota's premiere championship golf club, on May 20, 2019
    The tournament will be 18 holes, leaving more time for our golfers to enjoy dinner, along with our silent auction.
    ##### Schedule of Events:
    * 9:30 AM - Registration and hot breakfast buffet
    * 11:00 AM - Shotgun start
    * 3:30 PM - Social hour and silent auction
    * 5:00PM - Dinner (chef-carved prime rib) and awards
  image: "/uploads/somerbys_course.jpg"
sign_up:
  for_golfers and donors:
    text: 'Registration is easy. Simply create your fund easy page [here](https://secure.ministrysync.com/ministrysync/event/?e=16837).
      Once registered, you can direct potential donors to your site and share the
      link on Facebook and Twitter.  If you receive donations as cash or check, simply
      record the donations on your Fund Easy page, and bring the cash and checks to
      Somerby the day of the event. '
    button_link: 'https://secure.ministrysync.com/ministrysync/event/?e=16837      '
    button_text: I want to give!
  for_sponsors:
    text: 'We understand that not everyone is a golfer. However, there are sponsorship
      opportunities available, along with volunteer opportunities. For more information
      contact Jeff Jensen ([jeff.jensen@expresspros.com](mailto:jeff.jensen@expresspros.com?subject=Kid''s
      Cup Rochester Sponsorship)) or Marge Kelley ([marge.kelley@expresspros.com](mailto:marge.kelley@expresspros.com?subject=Kid''s
      Cup Rochester Sponsorship)). '
    button_link: mailto:marge.kelley@expresspros.com?subject=Kid's Cup Rochester Sponsorship
    button_text: I want to sponsor!
presenting_sponsors:
- image: "/uploads/express_logo.png"
  name: Express Employment Professionals
  link: https://www.expresspros.com/
corporate_sponsors:
- image: "/uploads/somerby_logo.jpg"
  name: Somerby Golf Club
  link: http://www.somerby.com/
- image: "/uploads/trina%20solano-3232f5.jpg"
  name: Trina Solano, Realtor
  link: https://www.edinarealty.com/trina-solano-realtor#/
other_sponsors:
- image: "/uploads/sams_club_logo.png"
  name: Sam's Club
  link: https://samsclub.com
- image: "/uploads/iheart_media_logo.png"
  name: iHeart Media
  link: https://www.iheartmedia.com/iheartmedia/stations?city=Rochester
- image: "/uploads/pro_image_logo.png"
  name: Pro Image
  link: http://www.proimageroch.com
- image: "/uploads/KIMT%20Logo%20-%20HQ%20.png"
  name: KIMT News 3
  link: https://www.kimt.com
- image: "/uploads/Ames%20Construction.JPG"
  name: Ames Construction
  link: https://www.amesconstruction.com/
- image: "/uploads/Sola.png"
  name: Sola Salon Studios
  link: https://www.solasalonstudios.com
- image: "/uploads/Morris%20Concrete.png"
  name: Morris Concrete, Inc.
  link: https://www.facebook.com/pages/Morris-Concrete/164999316859681
- image: "/uploads/Jaguar-5ecc29.JPG"
  name: Jaguar Communications
  link: https://www.jaguarcommunications.com/
- image: "/uploads/Capture.JPG"
  name: Johnson Printing
  link: http://www.johnson-printing.com/
